<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Global Manufacturing</name>
   <tag></tag>
   <elementGuidId>94d57f63-e71b-4e22-b661-fa2c44a701d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.headline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketingblock-1']/section/div/div/div/div/a/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6dcf6b1a-c7ce-4166-8450-c96873f8fd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>d6d5d3fa-9371-44a7-b924-dd52404dece6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Global Manufacturing</value>
      <webElementGuid>6d60d547-5ef2-4268-96ac-1605b4f5f1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketingblock-1&quot;)/section[@class=&quot;promo-block-container intel-ws&quot;]/div[@class=&quot;component-padding&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;wrapper wrapper-3&quot;]/a[@class=&quot;promo-block promo-block-3  no-gutter&quot;]/div[@class=&quot;text-container theme-dark-default&quot;]/h2[@class=&quot;headline&quot;]</value>
      <webElementGuid>9667a88c-46ae-4ee4-9ca8-7781d54d0bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketingblock-1']/section/div/div/div/div/a/div/h2</value>
      <webElementGuid>1097f701-5598-4178-91a8-dd76d61f5b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/h2</value>
      <webElementGuid>908f969e-c037-4cd3-b3c5-5dda3938b1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Global Manufacturing' or . = 'Global Manufacturing')]</value>
      <webElementGuid>793b225a-61bb-4fca-a157-609324410674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
