<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Deploy Comprehensive Manufacturing Globally</name>
   <tag></tag>
   <elementGuidId>19fdaa35-5c36-47be-a572-207048ecc9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navigationpageoverview-1']/div/div[2]/div[2]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3563cd2a-9c89-4b22-9b3a-9b1c8ec1a723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deploy Comprehensive Manufacturing Globally</value>
      <webElementGuid>4a24d9d3-ffb8-4752-8940-08e5da820441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigationpageoverview-1&quot;)/div[@class=&quot;marquee-nav-1_0_0 intel-ws color-block blade theme-classic-blue theme-dark-default brand-classic-blue-shade1 solid image-inset has-title&quot;]/div[@class=&quot;flex-block&quot;]/div[@class=&quot;marquee-layout layout-left&quot;]/div[@class=&quot;marquee-content color-block-lighter has-spark&quot;]/h1[1]</value>
      <webElementGuid>e077ff78-1b57-400e-a9ac-3410112c6ad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigationpageoverview-1']/div/div[2]/div[2]/div/h1</value>
      <webElementGuid>288fe508-3893-47ab-8806-6cda2a329c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3d3eef9d-5f5c-4e51-81b5-7b922962e6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Deploy Comprehensive Manufacturing Globally' or . = 'Deploy Comprehensive Manufacturing Globally')]</value>
      <webElementGuid>30f9089d-7efe-43e6-9c7e-b36bbff2b665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
