<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Sort</name>
   <tag></tag>
   <elementGuidId>131ba55c-4f53-4cc4-b772-3ea8b87b4d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accent-1']/section/div/div/div[2]/div/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>65cdba54-db95-46c1-ab83-dc7780565c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4 margin-btm-1x</value>
      <webElementGuid>cacaf5b2-d74f-4eb7-9bb7-e50dc2f6eea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Sort
        </value>
      <webElementGuid>857dbd87-833f-44b2-bd9c-b43c75a57f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accent-1&quot;)/section[@class=&quot;blade blade-featured-content image-on-mobile solid white theme-light-default link-default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;blade-item-container col-xs-12 col-sm-6 col-lg-4&quot;]/div[@class=&quot;blade-item&quot;]/div[@class=&quot;blade-item-content&quot;]/h3[@class=&quot;h4 margin-btm-1x&quot;]</value>
      <webElementGuid>13b8f19a-a387-4311-8645-194e7e3c58dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accent-1']/section/div/div/div[2]/div/div[2]/h3</value>
      <webElementGuid>ea7c7dde-a324-4f15-ae46-4898f980d7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/h3</value>
      <webElementGuid>1406914f-949a-4668-948e-33d0a4af9d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = '
            Sort
        ' or . = '
            Sort
        ')]</value>
      <webElementGuid>f9f991f2-3516-47cf-9c86-808cfbc858fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
