<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intel Ethernet Controller X710</name>
   <tag></tag>
   <elementGuidId>8aa149ad-31b7-4602-8fb5-cda2b64cf901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-content-product-select-1-3']/div/div[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>344468b7-5ae7-438c-8377-eee890632854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/content/www/us/en/products/details/ethernet/700-controllers/x710-controllers.html</value>
      <webElementGuid>c3b10ffa-630a-443f-b158-2beaca193c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intel® Ethernet Controller X710</value>
      <webElementGuid>48d0d569-d49c-4aa0-8cb5-a7d17bc10571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-content-product-select-1-3&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-sm-3&quot;]/div[@class=&quot;group-title has-name&quot;]/a[1]</value>
      <webElementGuid>554bff60-059d-4b10-9b6c-36a4f4f9160d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-content-product-select-1-3']/div/div[5]/div/a</value>
      <webElementGuid>f662b0dd-a8f9-4c8d-ab25-971aee26521e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intel® Ethernet Controller X710')]</value>
      <webElementGuid>bb545080-d781-49fb-8c65-ec150374447d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/content/www/us/en/products/details/ethernet/700-controllers/x710-controllers.html')]</value>
      <webElementGuid>53cb3bba-af31-4309-903d-bee9c5adf838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>070920d5-14c2-4edb-951b-9963cd963c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/content/www/us/en/products/details/ethernet/700-controllers/x710-controllers.html' and (text() = 'Intel® Ethernet Controller X710' or . = 'Intel® Ethernet Controller X710')]</value>
      <webElementGuid>cf6ceae8-9734-46c0-bbce-5dc3801980a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
