<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Programs</name>
   <tag></tag>
   <elementGuidId>cce43bbf-6644-4505-82e5-c316e0d31fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='udel1l2Template-1']/div/div[2]/div/div[2]/div/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c27cb91e-c045-4e1a-83cf-e17ef1ad0aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>atomCta</value>
      <webElementGuid>3a7ed7a3-fb06-4ea0-9065-149f418c10fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6e069580-ec7f-42b7-830e-1de6cdd07699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31306144-418a-4afa-b304-694b2a412c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/content/www/us/en/developer/programs/overview.html</value>
      <webElementGuid>9c57fd72-6d24-4fe6-812a-5605092cac03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programs</value>
      <webElementGuid>8ff0fb55-95cb-4142-9dc0-9bc1e408b32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udel1l2Template-1&quot;)/div[@class=&quot;onecolumn oneColumn&quot;]/div[@class=&quot;one-column component marquee-mosaic intel-ws force-background solid brand-blue-steel-shade1 theme-dark-default link-default full-bleed-cover&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;onecolumn parsys&quot;]/div[@class=&quot;listCTA section&quot;]/div[@class=&quot;scrollable-linklist&quot;]/div[@class=&quot;list-atomCta parsys&quot;]/div[@class=&quot;atomCta section&quot;]/div[1]/a[@class=&quot;a&quot;]</value>
      <webElementGuid>d0b2c9ea-76ca-43ac-9f51-cfb8dad35941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udel1l2Template-1']/div/div[2]/div/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>99d46924-c85c-47ed-9108-3ab88aaf3558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Programs')]</value>
      <webElementGuid>7535fe2e-588a-4e50-afe3-304be1eb46a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/content/www/us/en/developer/programs/overview.html')]</value>
      <webElementGuid>ce1ea76b-64a7-4c93-a20c-6b6baaa5da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>d3af17c9-ffa6-4564-97a2-09b14a114741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/content/www/us/en/developer/programs/overview.html' and (text() = 'Programs' or . = 'Programs')]</value>
      <webElementGuid>b121fd9a-ab6b-4ad8-b0a0-f77be4e2d885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
