<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Spaces</name>
   <tag></tag>
   <elementGuidId>88ef98e8-47c7-457e-b6b6-c7fda3ff32ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/spaces')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7958ab2-ab3d-42c3-b001-bbd042200bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex items-center px-2 py-0.5 dark:hover:text-gray-400 hover:text-blue-700</value>
      <webElementGuid>99975311-960a-4746-9092-2b31cea03758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/spaces</value>
      <webElementGuid>b6ecdef6-9c7e-40b3-a3e4-cd8ec0896901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Spaces</value>
      <webElementGuid>56d15b3e-61e7-4576-b635-0ffcd18d4276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flex flex-col min-h-screen bg-white dark:bg-gray-950 text-black DatasetsPage&quot;]/div[@class=&quot;flex min-h-screen flex-col&quot;]/div[@class=&quot;SVELTE_HYDRATER contents&quot;]/header[@class=&quot;border-b border-gray-100&quot;]/div[@class=&quot;w-full px-4 container flex h-16 items-center&quot;]/nav[@class=&quot;ml-auto hidden lg:block&quot;]/ul[@class=&quot;flex items-center space-x-1.5 xl:space-x-2&quot;]/li[3]/a[@class=&quot;group flex items-center px-2 py-0.5 dark:hover:text-gray-400 hover:text-blue-700&quot;]</value>
      <webElementGuid>438f974e-3e09-436d-ac37-bb690fb52582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/spaces')]</value>
      <webElementGuid>7c343608-f7e3-4a26-b869-53981d95b637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>68ede639-8bfb-4d84-9e79-255eccedaecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/spaces' and (text() = ' Spaces' or . = ' Spaces')]</value>
      <webElementGuid>857ddc93-02f6-4311-ab13-291f1dc3d48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
