<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c3109e02-e4e4-4ad9-9d8e-5bc997d76562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-lg.mb-3.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97166489-5393-49b5-ad2d-95c0df9fd6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg mb-3 w-full</value>
      <webElementGuid>be13d229-2a9e-4f0e-91f6-e0c895848a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8a66c4ea-5789-4073-8778-a333e2995847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login </value>
      <webElementGuid>175ee2c7-28d1-4424-814c-e16dd3a9d1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flex flex-col min-h-screen bg-white dark:bg-gray-950 text-black LoginPage&quot;]/div[@class=&quot;flex min-h-screen flex-col&quot;]/main[@class=&quot;flex flex-1 flex-col&quot;]/div[@class=&quot;container relative flex flex-col md:grid md:space-y-0 w-full md:grid-cols-12 md:flex-1 md:grid-rows-full space-y-4 md:gap-6 max-w-full bg-gradient-to-b from-indigo-100 via-orange-50 to-white dark:from-gray-900 dark:to-gray-925&quot;]/section[@class=&quot;pt-16 border-gray-100 col-span-full flex-1 pb-16 md:pb-0&quot;]/form[@class=&quot;z-10 mx-auto rounded-xl border bg-white p-4 shadow md:w-96&quot;]/div[2]/button[@class=&quot;btn btn-lg mb-3 w-full&quot;]</value>
      <webElementGuid>8c0e6a6f-1feb-49ad-b7a2-9c92d6ff8b94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>9881c022-1623-467b-94bb-5dc285736498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>db62c44f-4f11-4e93-90e1-da3116b7c236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login ' or . = 'Login ')]</value>
      <webElementGuid>3014d2a4-066b-4165-afb8-f03fc7204c5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
