<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_About</name>
   <tag></tag>
   <elementGuidId>c64d5cc0-2856-434d-9963-3827427173b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_1_Ar']/div/div/div/a[4]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2746f4f-483a-484a-916c-c514172b8a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_a2sa</value>
      <webElementGuid>e87ed368-ea0c-48b1-9fe6-abef79391f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>21040e21-3b6f-4b7f-8dcc-acbaa5d46dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_1_Ar&quot;)/div[@class=&quot;_7gbc&quot;]/div[@class=&quot;_8cm8&quot;]/div[@class=&quot;_7gbf&quot;]/a[@class=&quot;_8xc5 _8y8i _8x97 _8w61 _7gbg _8xc8 _8zvf&quot;]/span[@class=&quot;_8x6t _8x94 _8w61 _8w6h&quot;]/span[@class=&quot;_a2sa&quot;]</value>
      <webElementGuid>d970f41b-5864-4712-92ac-e83558cc377d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_1_Ar']/div/div/div/a[4]/span/span</value>
      <webElementGuid>608ff1ec-7fd3-4d9b-adbe-c695a0262932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/span/span</value>
      <webElementGuid>94417d5c-c2d9-4ed5-bee8-a78eb63eae31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'About' or . = 'About')]</value>
      <webElementGuid>99222c80-687e-440b-a434-2f69f18d96a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
