<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_IP Alliance</name>
   <tag></tag>
   <elementGuidId>3fd27081-9ed7-408a-96f0-d285e9a1d501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='multiasset-2']/section/div[2]/div/div/div/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4a68c2d5-c8a1-4931-8475-d77e309c9150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IP Alliance</value>
      <webElementGuid>cac622b1-43a5-491a-b8ab-98d3a1c2d59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiasset-2&quot;)/section[@class=&quot;l3-text-media-component blade media-top solid brand-lightest-gray-2 intel-ws link-default theme-light-default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row image-container&quot;]/div[@class=&quot;order-container&quot;]/div[@class=&quot;inner contentAlignmentParent&quot;]/div[@class=&quot;text-container col-xs-12 col-sm-7   clear-font&quot;]/h2[1]</value>
      <webElementGuid>17a54ea0-54ba-4a9b-acaa-841c08646777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='multiasset-2']/section/div[2]/div/div/div/div[2]/h2</value>
      <webElementGuid>f26aa7e9-3a20-4dae-8ad9-98d635367104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h2</value>
      <webElementGuid>af49bed0-a644-470b-a07c-7a8a5432573e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'IP Alliance' or . = 'IP Alliance')]</value>
      <webElementGuid>d5caccb0-7911-44f1-af9a-4eea269202fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
