<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Learn more</name>
   <tag></tag>
   <elementGuidId>398774fc-e464-47ea-84ba-a962c8fe7a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='multiasset-2']/section/div[2]/div/div/div/div[2]/p[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5604294-287a-4b34-afee-c9535d45c138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn more</value>
      <webElementGuid>f177798f-cc11-4909-910c-faa7513192b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiasset-2&quot;)/section[@class=&quot;l3-text-media-component blade media-top solid brand-lightest-gray-2 intel-ws link-default theme-light-default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row image-container&quot;]/div[@class=&quot;order-container&quot;]/div[@class=&quot;inner contentAlignmentParent&quot;]/div[@class=&quot;text-container col-xs-12 col-sm-7   clear-font&quot;]/p[@class=&quot;cta-item&quot;]/a[@class=&quot;btn btn-arrow btn-primary no-arrow&quot;]/span[1]</value>
      <webElementGuid>fcf38741-2730-4512-b739-0d214356289e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='multiasset-2']/section/div[2]/div/div/div/div[2]/p[3]/a/span</value>
      <webElementGuid>cc03f5da-44f2-4197-92b8-497264abe5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[3]/a/span</value>
      <webElementGuid>0f6a9d81-d966-49b9-bec1-a03d295f7bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Learn more' or . = 'Learn more')]</value>
      <webElementGuid>9aaabe0a-fa91-4793-a62c-4c0c927a7e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
