<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resources</name>
   <tag></tag>
   <elementGuidId>807b0a1f-ee2a-465e-91ae-9740e6b6cb4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_1_ek']/div/div/div/a[3]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afbca399-c3d4-4a7c-bd3e-65cf89a1dcda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_a2sa</value>
      <webElementGuid>51eca51a-4d3f-44ac-b79b-b74182c60a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>2ae20d0d-38a3-4afb-a89b-c8b434bb4071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_1_ek&quot;)/div[@class=&quot;_7gbc&quot;]/div[@class=&quot;_8cm8&quot;]/div[@class=&quot;_7gbf&quot;]/a[@class=&quot;_8xc5 _8y8i _8x97 _8w61 _7gbg _8xc8 _8zvf&quot;]/span[@class=&quot;_8x6t _8x94 _8w61 _8w6h&quot;]/span[@class=&quot;_a2sa&quot;]</value>
      <webElementGuid>b6e6376e-ff98-4938-801b-0bd54e426aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_1_ek']/div/div/div/a[3]/span/span</value>
      <webElementGuid>bb4285a3-59dd-42a6-bdbd-8943cfe0e112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span/span</value>
      <webElementGuid>367b6c2c-5201-4fa7-a3e4-a506a58cecbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Resources' or . = 'Resources')]</value>
      <webElementGuid>19d15eae-8e43-4c40-9ab9-79d276c36710</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
