<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Products</name>
   <tag></tag>
   <elementGuidId>f829c006-f873-45a7-8d83-736f44146d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trigger-menu-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='trigger-menu-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8bbe3cb-90fe-4ca3-81be-415b304cfa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b81999fe-3672-4824-b7c1-6d3f2accc4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-primary collapsed</value>
      <webElementGuid>06473f7d-237e-4db2-97b1-f6e0d895175c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap</name>
      <type>Main</type>
      <value>{&quot;linktype&quot;:&quot;level1&quot;}</value>
      <webElementGuid>3ac68045-d0b0-44f4-a8fd-eb6641c669f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trigger-menu-0</value>
      <webElementGuid>fde526e7-045e-4e0b-bf0a-73a0e52301d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#primary-nav</value>
      <webElementGuid>69f10bef-0c5a-427d-bf99-3eb028c5063d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#menu-0</value>
      <webElementGuid>9a1abb2c-9dcb-41f1-8baf-ee1e0e91e5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mega-control</name>
      <type>Main</type>
      <value>l1</value>
      <webElementGuid>dc94f68d-364d-490f-9e22-0f49ac12f0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a05c0088-3b3c-4f83-be6c-3ea564e42b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secure-link</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1adba023-929f-4e10-93b9-1cba7b657fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-0</value>
      <webElementGuid>9eff24dd-bcdd-43d5-9988-7e3ace8737a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>023e2162-e8e7-4e14-9369-db5086ac9d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trigger-menu-0&quot;)</value>
      <webElementGuid>7e1b3cec-d098-4795-adf3-fefa2265e180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='trigger-menu-0']</value>
      <webElementGuid>2222a86f-0b95-487c-90fc-c59bf4ff8394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-nav']/div/ol/li/button</value>
      <webElementGuid>1cdd27b6-a1fc-44c1-b2a5-3ce98b17962d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>5c14e00b-4261-481c-ac5e-099961bdf6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'trigger-menu-0' and (text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>9976c426-7bab-4c8a-ab9b-d6158b39b3fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
