<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_More</name>
   <tag></tag>
   <elementGuidId>b5c90abf-62ea-40a6-ae98-52383f8b05d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trigger-mega-more-panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='trigger-mega-more-panel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da86dadc-9932-4e0b-8332-b8036b25169c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap</name>
      <type>Main</type>
      <value>{&quot;linktype&quot;:&quot;level1&quot;}</value>
      <webElementGuid>b644af79-8c13-45c0-847b-72b70eba5c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e4eed33-80c8-40a9-bcd0-0389d3a75e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-primary collapsed</value>
      <webElementGuid>02cd4353-41e9-40a8-922e-ffc1458e457f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trigger-mega-more-panel</value>
      <webElementGuid>2d40bd05-2bc3-4b86-a7e8-e10853021d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mega-more-panel</value>
      <webElementGuid>7d497ffe-46ae-41c1-8fff-a5055f88cc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mega-control</name>
      <type>Main</type>
      <value>more-l1</value>
      <webElementGuid>34750f36-c652-4442-b8b8-4387f375bf0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd3a2953-e848-4bba-803f-44cc03665314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mega-more-panel</value>
      <webElementGuid>acfbbf9c-ed56-478b-96bd-1e217efa905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More +
    </value>
      <webElementGuid>d639b3f0-2205-4440-81f8-0b29b59175e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trigger-mega-more-panel&quot;)</value>
      <webElementGuid>77a1ef9f-a6c9-44ef-801a-6085be6c84aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='trigger-mega-more-panel']</value>
      <webElementGuid>f1d5afca-d2e0-42c6-a2e5-3bd8e0359eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-nav']/div/ol/li[5]/button</value>
      <webElementGuid>29c7a30d-de95-437e-8fdf-95e086a97c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/button</value>
      <webElementGuid>b44024c8-c946-4b49-a89e-d40612cf1cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'trigger-mega-more-panel' and (text() = 'More +
    ' or . = 'More +
    ')]</value>
      <webElementGuid>340cec9a-a554-4019-a689-c03c1cb52e08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
