<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Developers</name>
   <tag></tag>
   <elementGuidId>e5eeb924-b2c3-4928-b392-e8cd5278af99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trigger-menu-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='trigger-menu-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0968c789-ff2b-497d-9844-2c2653f421b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8776e3b3-9411-4192-aa16-7c0915fc499b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-primary collapsed</value>
      <webElementGuid>ed567309-9751-47e9-88ca-07c4b29c3200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap</name>
      <type>Main</type>
      <value>{&quot;linktype&quot;:&quot;level1&quot;}</value>
      <webElementGuid>a6682db4-311a-4ded-ad1a-5c8ea3b614d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trigger-menu-3</value>
      <webElementGuid>986e34e2-e4b8-4d11-ab28-89d580c6de16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#primary-nav</value>
      <webElementGuid>7888d2c5-9e84-48ce-9511-a266a9d82467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#menu-3</value>
      <webElementGuid>3f0afa80-e80c-4319-b042-31fa1010528f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mega-control</name>
      <type>Main</type>
      <value>l1</value>
      <webElementGuid>f4e4962d-a4ce-4d63-91ac-27ec0fda7f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f4b76a6-42d8-4637-825d-cafc21133e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secure-link</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>99dddee7-b554-43e8-8ffe-61a49bb04ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-3</value>
      <webElementGuid>8f4e5c71-ab71-424c-b51d-e6f8def7fcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Developers</value>
      <webElementGuid>1b7e5a5e-2813-42a5-925e-321c29cff3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trigger-menu-3&quot;)</value>
      <webElementGuid>63f446d0-2b47-48ff-ba1f-a4c692d3e06a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='trigger-menu-3']</value>
      <webElementGuid>e07a12d2-c7c5-4ab7-acff-fb4c302d69dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-nav']/div/ol/li[4]/button</value>
      <webElementGuid>a6d8ecd8-b538-4a61-9526-71d5cad0c32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>1fb3bbb2-41c1-4b54-8ce7-7665ac72e501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'trigger-menu-3' and (text() = 'Developers' or . = 'Developers')]</value>
      <webElementGuid>aa5ef840-c1c1-4f75-a03a-c5c12c00cec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
