<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Partners</name>
   <tag></tag>
   <elementGuidId>a016750b-316e-410a-bd08-dc5b25af5fad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trigger-menu-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='trigger-menu-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecafb69e-c905-47ad-b83a-8b71ca8dd94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1588cb16-cd9f-4331-981f-1818081e52eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-primary collapsed</value>
      <webElementGuid>22f752a7-30fc-4dea-83ed-462740080ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap</name>
      <type>Main</type>
      <value>{&quot;linktype&quot;:&quot;level1&quot;}</value>
      <webElementGuid>029ae4fc-781e-4218-b14e-ef53cc1f3830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trigger-menu-4</value>
      <webElementGuid>a8a32787-4ba7-4082-a4fa-3ad91c42f1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#primary-nav</value>
      <webElementGuid>5d6893b3-28eb-4c93-9751-e08881276be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#menu-4</value>
      <webElementGuid>c683a7a9-fccb-4003-ae7f-801bb8b6e784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mega-control</name>
      <type>Main</type>
      <value>l1</value>
      <webElementGuid>b250a4a4-ce89-495a-945f-535345be8275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4146f0df-dafe-4034-8233-4175bc84a558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secure-link</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>cf7cc0ba-a654-4c71-bee9-9a3321cb33d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-4</value>
      <webElementGuid>74d065c0-084f-484e-8368-c6a36b0b66de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Partners</value>
      <webElementGuid>1bb305e1-7544-487e-ae3c-55933bd253a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trigger-menu-4&quot;)</value>
      <webElementGuid>ec9fac2a-5fe1-4a9b-8145-def5a70dc80b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='trigger-menu-4']</value>
      <webElementGuid>cd5cb333-a4f9-4cdc-89d7-e0574a4061e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-nav']/div/ol/li[5]/button</value>
      <webElementGuid>a7b61250-8e6c-4331-afe2-22a7a74a7214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/button</value>
      <webElementGuid>20e8a18a-3a2d-4fdc-8ac4-f0851b2cbeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'trigger-menu-4' and (text() = 'Partners' or . = 'Partners')]</value>
      <webElementGuid>050bd593-b690-4a01-b8e9-415a56993fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
