<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Foundry</name>
   <tag></tag>
   <elementGuidId>e52172c2-ecb9-4046-98eb-e6b468d55133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trigger-menu-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='trigger-menu-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a3499cf-46d6-489a-99b4-cc6b0dcaf208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d28f010-1192-4b81-b458-335e47935f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-primary collapsed</value>
      <webElementGuid>005d0324-746e-45cd-b727-13509c71a5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap</name>
      <type>Main</type>
      <value>{&quot;linktype&quot;:&quot;level1&quot;}</value>
      <webElementGuid>601d19fc-fe48-4640-a25e-ce0adaec0ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trigger-menu-5</value>
      <webElementGuid>313c8cfb-cf98-4aec-b029-ae6a2017b281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#primary-nav</value>
      <webElementGuid>da7a299a-e6d8-4df7-8321-8c0e48cf45af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#menu-5</value>
      <webElementGuid>37041f2f-3461-4490-8b2a-5978ed77d268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mega-control</name>
      <type>Main</type>
      <value>l1</value>
      <webElementGuid>8f79efd7-fdac-42e9-8dc0-955451b05f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>805d9b1e-a8f9-4347-80b3-aaf1a7f33938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secure-link</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e08607c6-8dbc-420a-b05f-b31d514d5fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-5</value>
      <webElementGuid>190a2710-110e-4744-adfd-57380ac87b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foundry</value>
      <webElementGuid>0ce511a0-9e08-4478-ac8d-1b24c2256126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trigger-menu-5&quot;)</value>
      <webElementGuid>a56deb72-6a02-4867-9ccb-94ab69122c0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='trigger-menu-5']</value>
      <webElementGuid>7a952954-b8c4-4176-89e9-ed1b509b935f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mega-more-panel']/div/div/div/ol/li[2]/button</value>
      <webElementGuid>13da830b-57a3-402e-acac-7a513bb00ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/div/div/ol/li[2]/button</value>
      <webElementGuid>4ac06318-1b09-4f5b-aa8b-d141d4bede55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'trigger-menu-5' and (text() = 'Foundry' or . = 'Foundry')]</value>
      <webElementGuid>b5fe123c-d9bb-4b2b-865d-e8cbfd3dfdb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
