<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Services</name>
   <tag></tag>
   <elementGuidId>8e055574-e113-42fa-9c15-eb6435658700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-2']/div/div/div/div/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe7dbefd-e834-480a-9278-a9dcd6db724e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-l3</value>
      <webElementGuid>5af13c68-beff-49f5-ab24-afc0c422257d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap</name>
      <type>Main</type>
      <value>{&quot;category&quot;:&quot;solutions&quot;,&quot;sectiontype&quot;:&quot;subheading&quot;,&quot;linktype&quot;:&quot;level2&quot;}</value>
      <webElementGuid>20d47527-33c5-410e-8b3c-e02fc359af66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                            Services
                    </value>
      <webElementGuid>c8e14eb8-db89-4b51-8c6e-5b9009b9252a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-2&quot;)/div[@class=&quot;mega-panel-wrap&quot;]/div[@class=&quot;mega-panel-body&quot;]/div[@class=&quot;mega-body-wrap&quot;]/div[@class=&quot;panel-content flex-content-wrap&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;nav-l3&quot;]</value>
      <webElementGuid>e6da4a24-da48-483e-8f6b-08dd14ed96ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-2']/div/div/div/div/div[4]/div</value>
      <webElementGuid>cd91c6a7-9e20-41e7-a480-4a9b6c6d4cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/div/div/div[4]/div</value>
      <webElementGuid>a15186a3-a565-4197-b7fd-39245e6552b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        
                            Services
                    ' or . = '
                        
                            Services
                    ')]</value>
      <webElementGuid>b339a17f-5956-4e83-8fcf-f852656aafec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
