<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_fa-rb-support</name>
   <tag></tag>
   <elementGuidId>9acc817a-be60-4e65-aa35-4e14e29e0abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fa-rb-support</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homePageResourcesBar-1']/section/div/div[2]/ul/li/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8bc820f-3de5-46c0-9f3b-296d5e51e871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-rb-support</value>
      <webElementGuid>5598e0dc-f25f-4d52-96f6-b9ff68a473f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageResourcesBar-1&quot;)/section[@class=&quot;homepage-popular-resources blade theme-light-1 solid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;button-list visible&quot;]/ul[1]/li[@class=&quot;col-xs-6 col-sm-2&quot;]/a[@class=&quot;icon&quot;]/div[@class=&quot;fa-rb-support&quot;]</value>
      <webElementGuid>1eb72873-c773-47d4-a00e-32c226c146f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homePageResourcesBar-1']/section/div/div[2]/ul/li/a/div</value>
      <webElementGuid>463f3396-5dc1-4ffd-8626-e0e0d7630317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>6efda497-4d2c-4d83-97b1-420129edc197</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
