<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_See Products</name>
   <tag></tag>
   <elementGuidId>efa1a321-d0b6-4d40-be05-474b960911bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homePageResourcesBar-1']/section/div/div[2]/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e515a865-d470-40c6-aa6d-89ebed08b72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See Products</value>
      <webElementGuid>a7a6d703-ea9a-4bd8-a5fa-cc9ebdc8fa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageResourcesBar-1&quot;)/section[@class=&quot;homepage-popular-resources blade theme-light-1 solid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;button-list visible&quot;]/ul[1]/li[@class=&quot;col-xs-6 col-sm-2&quot;]/a[@class=&quot;icon&quot;]/span[1]</value>
      <webElementGuid>f1215e04-702b-4aae-a601-41722988842c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homePageResourcesBar-1']/section/div/div[2]/ul/li[3]/a/span</value>
      <webElementGuid>4686a8e2-ccc7-4660-8ca6-d14c6b7c93f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/ul/li[3]/a/span</value>
      <webElementGuid>c33d1d35-8e84-4311-98cf-555da3c38dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'See Products' or . = 'See Products')]</value>
      <webElementGuid>481388e9-08e8-44f9-b411-2e39f655415a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
