<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsignInName</name>
   <tag></tag>
   <elementGuidId>ce853415-f9c9-4f88-963c-afdb47b026cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>747feed3-9220-4710-a41b-ca78895642fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInName</value>
      <webElementGuid>018612e2-61ed-44a2-a040-dab1e12bd832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput</value>
      <webElementGuid>f36ad327-3ef6-48ae-b698-761581d7d954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f9aa2ce3-083e-4f3b-b8ab-fa16db0de1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>03a214c3-6f79-4b0f-84b5-3c66eb1e2977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>20ac72de-1ec6-4641-ac95-72c84ea77ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>086e32fe-6e71-42b7-b940-d3debd75cd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInName&quot;)</value>
      <webElementGuid>0fa2be50-539f-474e-9759-dbf979c1dd1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInName']</value>
      <webElementGuid>e9b71e34-5d53-44c7-b1c2-a7dc8d3f03a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attributeList']/ul/li/div/input</value>
      <webElementGuid>314c6a22-f41b-4b9d-b1f0-86b21712904f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>84caf95f-0cfd-4fa3-b2a3-093040bbac55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInName' and @type = 'email' and @title = 'Email']</value>
      <webElementGuid>d29ebf96-1389-43cd-ac85-d79eb86083b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
