<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blog</name>
   <tag></tag>
   <elementGuidId>fe23af29-1a0f-4aed-bcd9-1ba0d9358a54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_2_WC']/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a18446fa-23cf-4691-b1c0-d4b175559184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8xc5 _8y8i _8x97 _8w61 _7gbg _8xc8 _8zvf</value>
      <webElementGuid>f37c1785-99c1-454c-8364-85df1ca7786a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/blog/</value>
      <webElementGuid>e3d35943-dd99-4ca4-8351-4589a38b4e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ms</name>
      <type>Main</type>
      <value>{&quot;creative&quot;:&quot;link&quot;,&quot;creative_detail&quot;:&quot;link&quot;,&quot;create_type&quot;:&quot;link&quot;,&quot;create_type_detail&quot;:&quot;link&quot;}</value>
      <webElementGuid>f9d56c6c-45c6-4c30-b22d-e7e38741a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>a30c7ea4-8e15-4b07-be05-dc053cce9217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_2_WC&quot;)/div[@class=&quot;_7gbc&quot;]/div[@class=&quot;_8cm8&quot;]/div[@class=&quot;_7gbf&quot;]/a[@class=&quot;_8xc5 _8y8i _8x97 _8w61 _7gbg _8xc8 _8zvf&quot;]</value>
      <webElementGuid>139b9b01-0d51-4d2c-a8ab-d5fab7951bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_2_WC']/div/div/div/a[2]</value>
      <webElementGuid>1e78644f-3cc4-4150-835d-e9139770f98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/blog/')]</value>
      <webElementGuid>8f1d3894-93c8-41e5-9020-7aafec3f95b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>a02c77bf-52e8-422f-a5fb-3fb83df272b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/blog/' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>b9ad6fdd-51fb-490d-a7a6-7482c99ec1fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
