<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Research</name>
   <tag></tag>
   <elementGuidId>6321e50b-2b0f-42d3-b733-22b87538d2e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span._a2sa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_2_of']/div/div/div/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d978c01-23e8-414e-a7c2-a20ab21b2960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_a2sa</value>
      <webElementGuid>1dff828c-e184-45d2-a4f6-6efbca9f8b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Research</value>
      <webElementGuid>879e6fe7-423c-4a51-a912-bd59297cb6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_2_of&quot;)/div[@class=&quot;_7gbc&quot;]/div[@class=&quot;_8cm8&quot;]/div[@class=&quot;_7gbf&quot;]/a[@class=&quot;_8xc5 _8y8i _8x97 _8w61 _7gbg _7gbo _8xc8 _8zvf&quot;]/span[@class=&quot;_8x6t _8x94 _8w61 _8w6h&quot;]/span[@class=&quot;_a2sa&quot;]</value>
      <webElementGuid>48dd8e99-3e22-4936-a96e-ac42391aa804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_2_of']/div/div/div/a/span/span</value>
      <webElementGuid>d96e4474-fa51-423a-9677-903c8ce4d462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>5cf6efc7-b170-4950-b44a-2fadc56524d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Research' or . = 'Research')]</value>
      <webElementGuid>50b58cee-54fb-437d-a7eb-10be2c77cf62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
