<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>22714fd0-69de-4812-8d31-99b1e3ba2026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;IPA member&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotions-2']/section/div/div/div/div/figure/span/span[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>baad530c-2f97-464c-b18f-e3283df0565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>IPA member</value>
      <webElementGuid>ef94b1b8-f7e9-4f45-8eae-cc5ee3c69780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/content/dam/www/global/badges/a1148018-ipa-rwd.png.rendition.intel.web.416.234.png</value>
      <webElementGuid>9b39de0f-10b1-4309-8a30-b35a1e2c7bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>d842ec0e-0005-4777-84a8-60e03aa9025f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>201</value>
      <webElementGuid>1b670ac2-9651-4ee0-899c-136f392064e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>6167e7ee-a14c-42d9-9223-5acc8e12316c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotions-2&quot;)/section[@class=&quot;blade solid white theme-light-default intel-ws link-default blade-itemized blade-itemized-3 upe-promotion&quot;]/div[@class=&quot;container no-cursor-pointer&quot;]/div[@class=&quot;row promo-blade-container tile-centered-align blade-items itemized-listing&quot;]/div[@class=&quot;blade-item  col-xs-12 col-ms-6 col-sm-4 col-md-4 promotions-item mobilebreakpoint&quot;]/div[1]/figure[@class=&quot;blade-image&quot;]/span[@class=&quot;image-wh lazy-load-img&quot;]/span[4]/img[1]</value>
      <webElementGuid>5f5d869e-b831-4237-9746-2a910c5c84f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotions-2']/section/div/div/div/div/figure/span/span[4]/img</value>
      <webElementGuid>14734678-13ee-4252-a222-a403e7027f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='IPA member']</value>
      <webElementGuid>7901d555-32e1-4cd4-8043-4b2ad97be5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/img</value>
      <webElementGuid>5b2d9a58-fdca-491f-9e4f-43f5112d2b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'IPA member' and @src = '/content/dam/www/global/badges/a1148018-ipa-rwd.png.rendition.intel.web.416.234.png']</value>
      <webElementGuid>0e9c94c5-49a5-4fd8-b3d0-b5af182e076d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
