<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>b78ed05b-d677-4030-b256-a6c93346dab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;IPA titanium member&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotions-2']/section/div/div/div[3]/div/figure/span/span[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d235adc-7e0d-495a-bf23-071e36e4cac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>IPA titanium member</value>
      <webElementGuid>d0dd1ca4-75b6-4766-84c0-9cbb380a97ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/content/dam/www/global/badges/a1148018-ipa-titanium-rwd.png.rendition.intel.web.416.234.png</value>
      <webElementGuid>c6294f05-cc9a-4c23-bdd7-1e4481c91ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>0e420ee6-0e2e-47d3-ac68-bbfcef8d75dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>201</value>
      <webElementGuid>68cd4150-7512-46be-ad78-b612131e26a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c5a24ab4-f2c4-4d26-8306-44d10953e2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotions-2&quot;)/section[@class=&quot;blade solid white theme-light-default intel-ws link-default blade-itemized blade-itemized-3 upe-promotion&quot;]/div[@class=&quot;container no-cursor-pointer&quot;]/div[@class=&quot;row promo-blade-container tile-centered-align blade-items itemized-listing&quot;]/div[@class=&quot;blade-item  col-xs-12 col-ms-6 col-sm-4 col-md-4 promotions-item mobilebreakpoint&quot;]/div[1]/figure[@class=&quot;blade-image&quot;]/span[@class=&quot;image-wh lazy-load-img&quot;]/span[4]/img[1]</value>
      <webElementGuid>1bd147fd-d063-4803-9ae7-6ff5ee1871f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotions-2']/section/div/div/div[3]/div/figure/span/span[4]/img</value>
      <webElementGuid>c3a102bc-6873-47a3-bc47-716e1426a60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='IPA titanium member']</value>
      <webElementGuid>458f6627-c3ab-428d-b2b1-e2307be90ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/figure/span/span[4]/img</value>
      <webElementGuid>6f536031-e44e-4f4d-88a4-aed6c5883f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'IPA titanium member' and @src = '/content/dam/www/global/badges/a1148018-ipa-titanium-rwd.png.rendition.intel.web.416.234.png']</value>
      <webElementGuid>da4257f0-51b9-42c8-8f4d-739d0c85e0eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
