<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>54462fc5-789b-4d23-b7e7-5fd9e1b75b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;IPA gold member&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotions-2']/section/div/div/div[2]/div/figure/span/span[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>48770849-c6bb-4446-a00f-eb720022e647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>IPA gold member</value>
      <webElementGuid>44ac5f72-d61f-42c9-b9b7-2c012adbe2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/content/dam/www/global/badges/a1148018-ipa-gold-rwd.png.rendition.intel.web.416.234.png</value>
      <webElementGuid>7419df6c-f77c-4164-9933-d0f9313b97d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>358</value>
      <webElementGuid>72e71987-1145-4758-9ccf-7ac9250e3e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>201</value>
      <webElementGuid>e96c2609-98b0-46aa-8dd7-a8ed0ab5d34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>386cde9d-d23f-48f9-99ed-cc0e893a6969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotions-2&quot;)/section[@class=&quot;blade solid white theme-light-default intel-ws link-default blade-itemized blade-itemized-3 upe-promotion&quot;]/div[@class=&quot;container no-cursor-pointer&quot;]/div[@class=&quot;row promo-blade-container tile-centered-align blade-items itemized-listing&quot;]/div[@class=&quot;blade-item  col-xs-12 col-ms-6 col-sm-4 col-md-4 promotions-item mobilebreakpoint&quot;]/div[1]/figure[@class=&quot;blade-image&quot;]/span[@class=&quot;image-wh lazy-load-img&quot;]/span[4]/img[1]</value>
      <webElementGuid>5452cd8b-386b-462a-a98f-be1a812d1252</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotions-2']/section/div/div/div[2]/div/figure/span/span[4]/img</value>
      <webElementGuid>c755c252-a3d0-43c4-81f0-9f71740521e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='IPA gold member']</value>
      <webElementGuid>cab6c32b-5cde-45d3-a447-e165ed1e13a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/figure/span/span[4]/img</value>
      <webElementGuid>f4b623f8-0ffe-4371-9362-5fd409fb0722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'IPA gold member' and @src = '/content/dam/www/global/badges/a1148018-ipa-gold-rwd.png.rendition.intel.web.416.234.png']</value>
      <webElementGuid>4c02222f-e06e-4091-ad8a-57e31eaf3c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
