<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Real-Life Use Cases</name>
   <tag></tag>
   <elementGuidId>e688c28c-1d1c-453c-b411-81683e5b2e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ipa-tabs-component.tabs-overflow-component.blade.solid.theme-light-1.brand-lightest-gray-2 > div.intel-ws.theme-light-default.ipa-tabs.tabs-overflower.swipable > ul.scrolling-wrapper > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabBlade-2']/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e494cbc4-cb85-4a0c-81c0-db178593c79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-blade-2-1</value>
      <webElementGuid>ab09c4ab-9ec1-4d16-becd-4a47be154677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>real-life-use-cases</value>
      <webElementGuid>44dd1f1d-6898-4269-9457-24363ede3125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>de04265c-7a36-4dae-adc6-dfcc6b83a612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-blade-2-1</value>
      <webElementGuid>6d339523-c809-48ab-b267-ccc3e7b1f5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>dae14f27-4343-4f67-8a4e-7384e4c95d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Real-Life Use Cases</value>
      <webElementGuid>13fd634d-a51d-4c8e-a7bf-0542dcde3015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabBlade-2&quot;)/div[@class=&quot;ipa-tabs-component tabs-overflow-component blade solid theme-light-1 brand-lightest-gray-2&quot;]/div[@class=&quot;intel-ws theme-light-default ipa-tabs tabs-overflower swipable&quot;]/ul[@class=&quot;scrolling-wrapper&quot;]/li[2]/a[1]</value>
      <webElementGuid>655abbeb-612b-437f-8039-9a5cd3df3e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabBlade-2']/div/div/ul/li[2]/a</value>
      <webElementGuid>024b7f54-eaf7-4445-b3d2-e3965bbbe06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Real-Life Use Cases')]</value>
      <webElementGuid>a10f6413-c9a5-4c91-926e-d557251e07cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-blade-2-1')]</value>
      <webElementGuid>7ec0cb97-37fd-4c05-818b-392d103c0bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>a1eaed0a-f4ce-4474-ba54-4bf6a675d0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-blade-2-1' and (text() = 'Real-Life Use Cases' or . = 'Real-Life Use Cases')]</value>
      <webElementGuid>d1b2699d-e972-4a24-bbcc-b13b6ec4d9ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
