<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Technical Comparison</name>
   <tag></tag>
   <elementGuidId>22cd4aa9-106e-4250-9ea9-c3fa93798dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.scrolling-wrapper > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabBlade-2']/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>689419ad-a9f0-4003-8d9e-79d613575a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-blade-2-2</value>
      <webElementGuid>d1ee92d4-657c-488f-8758-5acf735bf8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>technical-comparison</value>
      <webElementGuid>07cb85eb-e801-4d4c-8ff7-d3f518ac5bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>35c6546a-0916-4eea-870e-ae965f649327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-blade-2-2</value>
      <webElementGuid>625ca122-ccf3-4288-92f7-cb6e33871b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>324d1fa0-907e-48cf-a345-546293cb1b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Technical Comparison</value>
      <webElementGuid>eb0ae076-be54-48e2-9cfd-a1649f4c45e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabBlade-2&quot;)/div[@class=&quot;ipa-tabs-component tabs-overflow-component blade solid theme-light-1 brand-lightest-gray-2&quot;]/div[@class=&quot;intel-ws theme-light-default ipa-tabs tabs-overflower swipable&quot;]/ul[@class=&quot;scrolling-wrapper&quot;]/li[3]/a[1]</value>
      <webElementGuid>2f764fd7-4912-4d8e-ab29-1624aedb065f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabBlade-2']/div/div/ul/li[3]/a</value>
      <webElementGuid>d1d7b16b-a4df-44e2-8769-50c6d301c3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Technical Comparison')]</value>
      <webElementGuid>9a41b432-ca9b-423e-ac82-5b8719a1316e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-blade-2-2')]</value>
      <webElementGuid>7a808581-3feb-4640-8438-4ff3f052c5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li[3]/a</value>
      <webElementGuid>eea46f90-bb6f-4010-8682-8016b312249b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-blade-2-2' and (text() = 'Technical Comparison' or . = 'Technical Comparison')]</value>
      <webElementGuid>e8eff55f-5b78-44be-a7fd-a68d329ae568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
