<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thunderbolt Technology Tips</name>
   <tag></tag>
   <elementGuidId>9b9c7e3d-e295-4d3a-b46b-38355e9732f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.scrolling-wrapper > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabBlade-2']/div/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cac2479-0aa3-456c-a71e-75fc29330c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-blade-2-3</value>
      <webElementGuid>d8c2ec07-f374-4122-8665-c2570610cf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>thunderbolt™-technology-tips</value>
      <webElementGuid>74493aaf-0fb6-4d51-9400-5ed6960ce61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5faec268-1e5c-4b47-8dca-64b9ad927326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-blade-2-3</value>
      <webElementGuid>c8921ddb-8411-45a6-bd7f-e901fba8536e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>92eea67c-e938-436d-bb49-08cc20c83cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thunderbolt™ Technology Tips</value>
      <webElementGuid>1a273b21-988d-4d62-a4f2-d5d07412cb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabBlade-2&quot;)/div[@class=&quot;ipa-tabs-component tabs-overflow-component blade solid theme-light-1 brand-lightest-gray-2&quot;]/div[@class=&quot;intel-ws theme-light-default ipa-tabs tabs-overflower swipable&quot;]/ul[@class=&quot;scrolling-wrapper&quot;]/li[4]/a[1]</value>
      <webElementGuid>5329e789-792a-4ebf-bcf0-cacd1bb8de73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabBlade-2']/div/div/ul/li[4]/a</value>
      <webElementGuid>66b5d22c-93e2-4123-88a6-9130f460edf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thunderbolt™ Technology Tips')]</value>
      <webElementGuid>16484d0c-ac66-44d5-8b82-1fd2255836c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-blade-2-3')]</value>
      <webElementGuid>e852d999-bf7e-4fd0-b169-95102768f730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li[4]/a</value>
      <webElementGuid>8f0968fd-90bb-4130-9161-82136411b958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-blade-2-3' and (text() = 'Thunderbolt™ Technology Tips' or . = 'Thunderbolt™ Technology Tips')]</value>
      <webElementGuid>f4713168-8664-421b-9be6-20fcf76b9094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
