<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pricing</name>
   <tag></tag>
   <elementGuidId>3984cb29-7724-4baf-9ca1-43fd3c75b26d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Pricing')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>360c53f3-566c-4302-827a-93730adff1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex items-center px-2 py-0.5 hover:text-gray-500 dark:hover:text-gray-400</value>
      <webElementGuid>4cd39169-9da4-43ae-982b-2a7a4dd882f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pricing</value>
      <webElementGuid>041f1b22-6930-47ce-9e51-107bcb9d8217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing</value>
      <webElementGuid>69b71f44-8f9b-4865-afcc-0f622abbdb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flex flex-col min-h-screen bg-white dark:bg-gray-950 text-black DocsPage&quot;]/div[@class=&quot;flex min-h-screen flex-col&quot;]/div[@class=&quot;SVELTE_HYDRATER contents&quot;]/header[@class=&quot;border-b border-gray-100&quot;]/div[@class=&quot;w-full px-4 container flex h-16 items-center&quot;]/nav[@class=&quot;ml-auto hidden lg:block&quot;]/ul[@class=&quot;flex items-center space-x-1.5 xl:space-x-2&quot;]/li[7]/a[@class=&quot;group flex items-center px-2 py-0.5 hover:text-gray-500 dark:hover:text-gray-400&quot;]</value>
      <webElementGuid>79b3a276-aefe-4b5b-aa31-ce0ffa6a7095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pricing')]</value>
      <webElementGuid>0b52bbce-6704-426e-9e3c-dde8e78a3dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pricing')]</value>
      <webElementGuid>bd9b9fd7-376c-48f4-9a7b-e353253cd853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>d08c2537-623b-4ff4-863e-10e256a3a71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pricing' and (text() = 'Pricing' or . = 'Pricing')]</value>
      <webElementGuid>f29462ad-6f8f-42e4-a149-13c87e0b01a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
