<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Applications</name>
   <tag></tag>
   <elementGuidId>f5203ea5-02a5-4230-9d03-0e4d2ddba841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.scrolling-wrapper > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabBlade-1']/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b721ed31-54be-4be1-b468-dd629f443761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-blade-1-1</value>
      <webElementGuid>2a64c6c4-ca21-4488-941d-39ff604d03c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>applications</value>
      <webElementGuid>8c502bce-02f6-42f1-b884-175f37c5ea1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>affdbb39-3004-4552-8f28-88c34e98346f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-blade-1-1</value>
      <webElementGuid>451c2e1d-6ff4-44b0-b842-af4b9e296ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a9c27df5-1215-492f-a5aa-d20b45b69eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Applications</value>
      <webElementGuid>98a114fc-8461-4aae-98f8-69f905c34d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabBlade-1&quot;)/div[@class=&quot;ipa-tabs-component tabs-overflow-component blade solid theme-light-1&quot;]/div[@class=&quot;intel-ws theme-light-default ipa-tabs tabs-overflower swipable&quot;]/ul[@class=&quot;scrolling-wrapper&quot;]/li[2]/a[1]</value>
      <webElementGuid>a9d37b06-f9b9-43f6-bc10-34398b6e74c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabBlade-1']/div/div/ul/li[2]/a</value>
      <webElementGuid>ebccfa48-824b-4f5f-9a4f-3a9da6eb3d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Applications')]</value>
      <webElementGuid>884dfa6d-af6a-43a4-bcbb-77a61eb94c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-blade-1-1')]</value>
      <webElementGuid>63ffcc23-32cf-467f-ae41-e9f520f4a314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>943e6124-b6f5-43d7-864f-ad7db502ae4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-blade-1-1' and (text() = 'Applications' or . = 'Applications')]</value>
      <webElementGuid>9d7f3ed3-6541-431c-b3a5-f476d707d1ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
