<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Support</name>
   <tag></tag>
   <elementGuidId>93047ace-f71c-4641-a892-1c273b8dd55a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.scrolling-wrapper > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabBlade-1']/div/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c41314f2-260e-4e43-89fb-682ad5848343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-blade-1-3</value>
      <webElementGuid>4c475ad7-6c82-4c25-b8f0-0bf49982905d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>support-</value>
      <webElementGuid>8fbdff83-4c71-40c3-8245-44240d9e4616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>96ba5e22-3c41-47c3-a11e-00dccd1c18c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-blade-1-3</value>
      <webElementGuid>c73cf861-5a80-40a4-ae49-1d4c4e64d8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>cd42e186-ef6e-4721-a985-3031d46d257f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Support </value>
      <webElementGuid>c036251c-bc0b-4ded-85e2-2bd9869aeb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabBlade-1&quot;)/div[@class=&quot;ipa-tabs-component tabs-overflow-component blade solid theme-light-1&quot;]/div[@class=&quot;intel-ws theme-light-default ipa-tabs tabs-overflower swipable&quot;]/ul[@class=&quot;scrolling-wrapper&quot;]/li[4]/a[1]</value>
      <webElementGuid>738d5366-309b-44c8-9f17-c1c9400a22c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabBlade-1']/div/div/ul/li[4]/a</value>
      <webElementGuid>8c0a47fc-afa9-4a15-898f-30049bca58cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Support')])[2]</value>
      <webElementGuid>00342c96-056a-43c5-a35f-51cefc93302d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-blade-1-3')]</value>
      <webElementGuid>ba069baa-2c06-41f7-8a28-fda17ef9e0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[4]/a</value>
      <webElementGuid>e4c74920-cd91-4090-816d-2d41e69df52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-blade-1-3' and (text() = 'Support ' or . = 'Support ')]</value>
      <webElementGuid>28bd4cff-492f-4603-96a3-dcead1c64719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
