<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automotive</name>
   <tag></tag>
   <elementGuidId>5479783e-04f0-47e2-bf09-0acd784c57b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.scrolling-wrapper > li:nth-of-type(6) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabBlade-1']/div/div/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4bd36ea-1283-4768-987e-cb1299c6dd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-blade-1-5</value>
      <webElementGuid>cdacb190-0e90-4938-a0b2-624b02ff870b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>automotive</value>
      <webElementGuid>29e3d40c-b71e-4d33-bdf8-6dfd9bb5d9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>75889625-7b96-4fa6-ae78-036419378fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-blade-1-5</value>
      <webElementGuid>65cf3e29-bc66-467f-af8f-d8b09bc7b197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6b3de32e-a6a8-41f0-b70f-ca1017a04395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automotive</value>
      <webElementGuid>557a3d3a-17eb-4365-8b79-9de18bddf2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabBlade-1&quot;)/div[@class=&quot;ipa-tabs-component tabs-overflow-component blade solid theme-light-1 brand-lightest-gray-2 fullbleed-mode&quot;]/div[@class=&quot;intel-ws theme-light-default ipa-tabs tabs-overflower swipable&quot;]/ul[@class=&quot;scrolling-wrapper&quot;]/li[6]/a[1]</value>
      <webElementGuid>87574878-425d-41af-9c04-1a55226f6ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabBlade-1']/div/div/ul/li[6]/a</value>
      <webElementGuid>600fb67c-6b5d-4897-906a-77062dfea088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Automotive')]</value>
      <webElementGuid>692a367c-8b2a-4126-9671-7fd272fd92a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-blade-1-5')]</value>
      <webElementGuid>8da0a199-df92-419f-81ed-9a1f64f565ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/ul/li[6]/a</value>
      <webElementGuid>48c270ff-499e-4644-90f5-0eaffc8688ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-blade-1-5' and (text() = 'Automotive' or . = 'Automotive')]</value>
      <webElementGuid>33eef624-e2b5-41c6-97dd-f1d7bb99680c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
