<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enhancing LLMs on cnvrg.io</name>
   <tag></tag>
   <elementGuidId>0c76af1e-fba8-44b3-b86c-82e41896f9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.blade-item-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='promo-main-heading-4']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48d0b5b0-1aed-4023-8e63-bf32429efa62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cnvrg.io/enhance-large-language-models-leveraging-rag-and-minio-and-cnvrg/</value>
      <webElementGuid>ec557701-a8cf-4d62-bba7-1dd6ac694989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blade-item-link</value>
      <webElementGuid>94a7f1b5-af61-4ff6-82e4-cf1187108fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enhancing LLMs on cnvrg.io</value>
      <webElementGuid>3f6eaf7b-f8c8-4374-802f-02488bcddbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo-main-heading-4&quot;)/a[@class=&quot;blade-item-link&quot;]</value>
      <webElementGuid>61e8c6b2-9b24-41c5-bfb4-ae763c25bbb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='promo-main-heading-4']/a</value>
      <webElementGuid>49046f7f-0122-4b26-b0be-b16dc8fd7360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enhancing LLMs on cnvrg.io')]</value>
      <webElementGuid>67e5ae04-fd11-4651-8304-f8c7ea65ed1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://cnvrg.io/enhance-large-language-models-leveraging-rag-and-minio-and-cnvrg/')])[2]</value>
      <webElementGuid>9adc9b02-036b-442b-a38c-5e8b13df6565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>2ccb37f4-029c-466f-8916-145bbf27d97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cnvrg.io/enhance-large-language-models-leveraging-rag-and-minio-and-cnvrg/' and (text() = 'Enhancing LLMs on cnvrg.io' or . = 'Enhancing LLMs on cnvrg.io')]</value>
      <webElementGuid>66dbc184-166b-40a5-9b18-262f0aa4134d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
