<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_News  Ideas</name>
   <tag></tag>
   <elementGuidId>a4e10fca-3498-4762-8ac8-f541ea09a776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageContent']/header/div[2]/div/div/div/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88cfbd5e-965e-4aa1-ba14-cf2b3b34e699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>News &amp; Ideas</value>
      <webElementGuid>c7f671d2-d10a-4f24-a9c1-42d0a4532b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#promotions_568607639</value>
      <webElementGuid>936036bb-7049-465f-8eb5-8c5ccde44511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News &amp; Ideas</value>
      <webElementGuid>c40ec41e-9714-4d35-bf20-d41aaf40b1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContent&quot;)/header[@class=&quot;has-jumplinks&quot;]/div[@class=&quot;jumplinksContainer&quot;]/div[@class=&quot;jumplinks jumplink rwd-jumplinks&quot;]/div[@class=&quot;nav-overflower spynav nav-spy component fix-depth&quot;]/div[@class=&quot;wrap-1 nav-affixer affix&quot;]/div[@class=&quot;wrap-2 overflower&quot;]/ul[@class=&quot;nav overflower-inner&quot;]/li[@class=&quot;overflower-item&quot;]/a[1]</value>
      <webElementGuid>50565448-d4dc-4046-9075-9b252fdeb5f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageContent']/header/div[2]/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>6edbd6a4-d8f6-46fc-bad6-0583afc880a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'News &amp; Ideas')]</value>
      <webElementGuid>895d12e0-ab21-4d1c-9184-e2b1ce5f19de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#promotions_568607639')]</value>
      <webElementGuid>b424333c-040f-4793-9b25-ae82bbe24fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>90f5c8d6-6264-4779-8b04-6fb2154df637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#promotions_568607639' and (text() = 'News &amp; Ideas' or . = 'News &amp; Ideas')]</value>
      <webElementGuid>eb71296f-3682-487a-87b6-8b1d2f0e31b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
