<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Resources</name>
   <tag></tag>
   <elementGuidId>f9350fb8-58f3-4408-8efa-90c6e79dc32c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageContent']/header/div[2]/div/div/div/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0298f91-24d9-4f73-ae02-282a1ec8ebdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wap_ref</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>5da9484a-3aac-4749-b665-8417611682b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#simplecard_copy</value>
      <webElementGuid>3fe718db-8058-40b8-848a-a07476996699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>9475351f-ca65-47bd-a5f7-aae82891c208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageContent&quot;)/header[@class=&quot;has-jumplinks&quot;]/div[@class=&quot;jumplinksContainer&quot;]/div[@class=&quot;jumplinks jumplink rwd-jumplinks&quot;]/div[@class=&quot;nav-overflower spynav nav-spy component fix-depth&quot;]/div[@class=&quot;wrap-1 nav-affixer affix&quot;]/div[@class=&quot;wrap-2 overflower&quot;]/ul[@class=&quot;nav overflower-inner&quot;]/li[@class=&quot;overflower-item&quot;]/a[1]</value>
      <webElementGuid>42424ddd-552b-47aa-a952-95bd3fa9e07e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageContent']/header/div[2]/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>6a546471-471b-4972-8a57-434d4ffae207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Resources')]</value>
      <webElementGuid>b98f6c71-aba9-46c1-b80b-1f6de40e7ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#simplecard_copy')]</value>
      <webElementGuid>bc0f4191-8ac8-43f0-8cde-e28d47e1ac0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>19d98129-e9fe-435c-b34a-b286ca7e7160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#simplecard_copy' and (text() = 'Resources' or . = 'Resources')]</value>
      <webElementGuid>6759c4c0-9ece-48df-b59a-370c52c134a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
