<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_AI</name>
   <tag></tag>
   <elementGuidId>2071ebf2-111c-4dc8-bab4-b68a3bc175cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketingblock-1']/section/div/div/div/div/a[2]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>023a5810-0998-4a00-9e78-4653e2ec28c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>d31e9afc-7d5f-4d46-91f5-b9c6c21a6ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AI</value>
      <webElementGuid>9f5b7f4f-9ded-479b-b9fb-aea125c9c04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketingblock-1&quot;)/section[@class=&quot;promo-block-container intel-ws&quot;]/div[@class=&quot;component-padding&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;wrapper wrapper-3&quot;]/a[@class=&quot;promo-block promo-block-3  no-gutter&quot;]/div[@class=&quot;text-container theme-dark-default&quot;]/h2[@class=&quot;headline&quot;]</value>
      <webElementGuid>4c9d8864-6030-4198-bc0e-804eef7438a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketingblock-1']/section/div/div/div/div/a[2]/div/h2</value>
      <webElementGuid>c2eec6fd-0fab-4277-a6e4-485264077b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/h2</value>
      <webElementGuid>96537208-481b-4e7b-8f48-faddaa89b585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'AI' or . = 'AI')]</value>
      <webElementGuid>959884e5-0f14-4dca-a7ef-bd72f5dbf43a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
