<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Developer Software Forums</name>
   <tag></tag>
   <elementGuidId>b0951663-1866-4d39-ade7-c8a874652e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-horizontal-nav']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca90f6b6-1ad3-475a-9094-a82c0e83118d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>b9a3b93b-b4ac-4d00-8577-d4576ce84215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-level-link menuitem</value>
      <webElementGuid>76e09cb0-9b7a-4c4c-8255-af6ffa1cbbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49e15ed8-2f3d-4b3c-a03b-e9cb51288a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/t5/Developer-Software-Forums/ct-p/developer-software-forums</value>
      <webElementGuid>f3133b9e-8628-4fa0-b053-67b22951834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Developer Software Forums</value>
      <webElementGuid>9d68291a-b672-4bfb-9bf3-de97478dfd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>52c894bf-81d2-4a81-8693-5873a3f0d720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Developer Software Forums</value>
      <webElementGuid>846fa6d2-14bd-41fa-b882-19c75ad7767e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-horizontal-nav&quot;)/ul[@class=&quot;custom-sub-nav visible-lg-block&quot;]/li[@class=&quot;has-children&quot;]/a[@class=&quot;top-level-link menuitem&quot;]</value>
      <webElementGuid>9b5510d9-5b2d-4269-ac38-eb5f34538f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-horizontal-nav']/ul/li[4]/a</value>
      <webElementGuid>6bdecb53-a30a-465a-9bd6-6dde18633a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Developer Software Forums')]</value>
      <webElementGuid>654c08f1-23a5-462e-980e-ec60aacb3580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/t5/Developer-Software-Forums/ct-p/developer-software-forums')]</value>
      <webElementGuid>9121ee38-980d-4acd-b474-d70056f0f6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[4]/a</value>
      <webElementGuid>362ef810-e1db-4970-b744-75dc286121b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/t5/Developer-Software-Forums/ct-p/developer-software-forums' and (text() = 'Developer Software Forums' or . = 'Developer Software Forums')]</value>
      <webElementGuid>5f856122-8282-4edd-ba87-13e0bb94c14a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
