<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gaming Forums</name>
   <tag></tag>
   <elementGuidId>6b03f655-1229-446b-b633-cf015d70ef0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-horizontal-nav']/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ccef5dda-1b82-4d0d-9811-14e2645d1458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>36561aeb-5efe-4fde-822b-a4af776857e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-level-link menuitem</value>
      <webElementGuid>290c7855-3b97-482a-bc98-ad1257fa47b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f891aba0-69a5-4a0c-9f25-8cf74aaf8d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/t5/Gaming-Forums/ct-p/gaming-community</value>
      <webElementGuid>c2203b5e-d396-4673-803b-0b6eda17bde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Gaming Forums</value>
      <webElementGuid>f6456baf-d2c8-4c01-8c30-91f753567d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cdbaab0f-2143-425f-8df8-a403a5267e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gaming Forums</value>
      <webElementGuid>b3679245-1e8d-40c0-be0d-f7db8bbe374b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-horizontal-nav&quot;)/ul[@class=&quot;custom-sub-nav visible-lg-block&quot;]/li[@class=&quot;has-children&quot;]/a[@class=&quot;top-level-link menuitem&quot;]</value>
      <webElementGuid>c7e2c460-f2c5-4999-947b-7dc442e19de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-horizontal-nav']/ul/li[6]/a</value>
      <webElementGuid>fc78b123-c65d-4837-8f59-9f4e1d33811f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gaming Forums')]</value>
      <webElementGuid>5f4781a5-f13c-4822-8cc3-c04179010f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/t5/Gaming-Forums/ct-p/gaming-community')]</value>
      <webElementGuid>31a3299d-cba4-4af4-9bd8-3c101887748f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[6]/a</value>
      <webElementGuid>307a086a-0a5c-418f-85dd-92225955569c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/t5/Gaming-Forums/ct-p/gaming-community' and (text() = 'Gaming Forums' or . = 'Gaming Forums')]</value>
      <webElementGuid>464349db-f83e-4e0a-ba69-4eaa7362c7a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
