<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Product Support Forums</name>
   <tag></tag>
   <elementGuidId>62dfaaeb-582e-48ad-8003-628f9a146f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-horizontal-nav']/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e723a20-a7c1-482c-8726-9864844377bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4cc64190-e356-43bc-ac1f-6536a678ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-level-link menuitem</value>
      <webElementGuid>d3633e28-5f8f-4dac-b671-c41a9db9843a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>598da259-fc33-4f25-84d1-05613f668432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/t5/Product-Support-Forums/ct-p/product-support-forums</value>
      <webElementGuid>596374ed-ffc3-448f-be40-a4b5b05341ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Product Support Forums</value>
      <webElementGuid>63f3e03e-86c5-49c0-a594-d21ae2a8eeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>65a936e3-295b-42f5-9cae-8c642bd02421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Support Forums</value>
      <webElementGuid>cb494067-9161-4b28-b4e9-6c6a7deafdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-horizontal-nav&quot;)/ul[@class=&quot;custom-sub-nav visible-lg-block&quot;]/li[@class=&quot;has-children&quot;]/a[@class=&quot;top-level-link menuitem&quot;]</value>
      <webElementGuid>58ea0944-0cb2-49ec-8d4a-a0a09f2ea442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-horizontal-nav']/ul/li[5]/a</value>
      <webElementGuid>11fb010f-33f9-4f71-9020-d15b0a14cfac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Product Support Forums')]</value>
      <webElementGuid>3de218fa-dcde-49d3-91d7-ede592f67795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/t5/Product-Support-Forums/ct-p/product-support-forums')]</value>
      <webElementGuid>03cc4644-b417-428f-8cd1-5e46327cf558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[5]/a</value>
      <webElementGuid>4a4f7e6f-1cd6-4490-8cad-963cab3f2116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/t5/Product-Support-Forums/ct-p/product-support-forums' and (text() = 'Product Support Forums' or . = 'Product Support Forums')]</value>
      <webElementGuid>571a63b5-677d-4213-aedc-9fe037628768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
