<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>513119db-90a3-4454-bc6e-49fb3f0b0556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Intel® evo™ laptops product image&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotions-1']/section/div/div/div/div/figure/a/span/span[5]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8e61de6-04e9-4e39-a7eb-03b2ed04f4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Intel® evo™ laptops product image</value>
      <webElementGuid>03ea4ad6-6448-4f1f-8286-026339dcce0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/content/dam/www/central-libraries/us/en/images/2022-08/evo-laptop-product-image-transparent-background.png.rendition.intel.web.576.324.png</value>
      <webElementGuid>f02f50ff-83f3-463d-8398-871040135625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>261</value>
      <webElementGuid>a154f6ee-e4c0-48dd-b937-72543ba09548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>88c09d84-8b6f-404c-9509-52980c4e93c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d3b4ca5c-9e89-4c57-a8b8-04426a54ff41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotions-1&quot;)/section[@class=&quot;blade solid white theme-light-default intel-ws link-default blade-itemized blade-itemized-4 upe-promotion&quot;]/div[@class=&quot;container no-cursor-pointer&quot;]/div[@class=&quot;row promo-blade-container tile-centered-align blade-items itemized-listing&quot;]/div[@class=&quot;blade-item  col-xs-12 col-ms-6 col-sm-6 col-lg-3 promotions-item&quot;]/div[1]/figure[@class=&quot;blade-image&quot;]/a[@class=&quot;intel-ws-ignore&quot;]/span[@class=&quot;image-wh lazy-load-img&quot;]/span[5]/img[1]</value>
      <webElementGuid>40e614ea-85ff-4f1c-85cd-59e1ec224e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotions-1']/section/div/div/div/div/figure/a/span/span[5]/img</value>
      <webElementGuid>f42ba8a9-3eff-4ed3-a4fe-1f45dd879fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Intel® evo™ laptops product image']</value>
      <webElementGuid>9fb2b648-30dc-435b-a195-cdb9794410c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/span[5]/img</value>
      <webElementGuid>5bca6cdd-b790-4b25-86fd-2e5fd72f1620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Intel® evo™ laptops product image' and @src = '/content/dam/www/central-libraries/us/en/images/2022-08/evo-laptop-product-image-transparent-background.png.rendition.intel.web.576.324.png']</value>
      <webElementGuid>cbf3b061-8afb-499b-92f1-7dc13a1b9531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
